related to bug 29284: added test cases to cover onCreateDefault behavior
  Bug #29284 makes two of these test cases fail in Oracle:

    nonMandatoryOnCreateDefault[DB: oracle - append](org.openbravo.dbsm.test.model.data.CreateDefault)
    java.lang.AssertionError: Value for column NM2
    Expected: "A"
         but: was null

    nonMandatoryDifferentDefaultAndOnCreateDefault[DB: oracle - append](org.openbravo.dbsm.test.model.data.CreateDefault)
    java.lang.AssertionError: Value for column NM4
    Expected: "B"
         but: was "A"